export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as NotFound } from "./NotFound";
export { default as Signup } from "./Signup";
export { default as Welcome } from "./Welcome";
export { default as AuthProvider } from "./AuthProvider";
export { default as Loader } from "./common/Loader";
export { default as Art } from "./Art";
export { default as CreateArt } from "./CreateArt";
export { default as EditArt } from "./EditArt";
export { default as ArtList } from "./ArtList";
export { default as Explore } from "./Explore";
export { default as UpdateUser} from "./UpdateUser";
export { default as UserProfile } from "./common/UserProfile";
